# Generated by Django 4.2.7 on 2024-12-14 14:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('elevation_profile', models.JSONField(blank=True, null=True)),
                ('difficulty_rating', models.SmallIntegerField()),
                ('length_meters', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
