# Generated by Django 4.2.7 on 2024-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='difficulty_rating',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='length_meters',
            field=models.FloatField(db_index=True),
        ),
    ]
