# Generated by Django 4.2.7 on 2024-12-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_alter_trail_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trails_pics/'),
        ),
    ]
