# Generated by Django 4.2.7 on 2024-12-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_trail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='created_by',
            new_name='username',
        ),
    ]
