# Generated by Django 4.2.7 on 2024-12-18 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trails', '0004_rename_created_by_trail_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trail',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
