# Generated by Django 4.2.7 on 2024-12-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_trail_created_by_alter_trail_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='username',
        ),
    ]
