# Generated by Django 4.2.7 on 2024-12-14 17:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrailStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('recorded_path', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='trails.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
